version: '3.2'

#
# Run this integration test by running:
# ID=$(docker build -q .) && LOCAL_IMAGE_ID=$ID docker-compose -f docker-compose-integration-tests.yml up --abort-on-container-exit --always-recreate-deps
#

services:
  #############################################
  # Start app as a container
  #############################################
  web:
    # if not --build and kth-azure-app already exists in
    # your local computers registry 'image' is used.

    # build: . 
    image: $LOCAL_IMAGE_ID

    # LOCAL_IMAGE_ID, IMAGE_NAME and IMAGE_VERSION

    # Since we do not want to add tests to our 
    # production image. We mount the catalog
    # 'tests' on in the repo on your local machine
    # to /tests on the inside of the container.
    # The volume mount is done at startup.
    volumes:
      - ./tests:/tests

    # The unit test command that triggers tests to be run
    # inside the container
    # This example runs test in package.json which is
    # part of the image.
    command: npm test

